# Exclude lab3.py from all ruff checks
exclude = ["lab3.py", "analyze_vocabulary.py"]

[lint]
# Enable flake8-bugbear (`B`) rules.
select = ["E", "F", "B", "I"]

# Never enforce `E501` (line length violations).
ignore = ["E501", "E741", "B905"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
"embeddings.py" = ["E501"]
